Alter table MOV_REUNIAO
 DROP CONSTRAINT FK_CAD_REUNIAOxMOV_REUNIAO;

Alter table MOV_REUNIAO
 DROP CONSTRAINT FK_COD_MOD_REUNIAOxMOV_REUNIAO;

Alter table CAD_PROGRAMA
 DROP CONSTRAINT  CK_CAD_PARTEXCAD_PROGRAMA;
 
Alter table CAD_PROGRAMA
  ADD COD_TP_REUNIAO SMALLINT DEFAULT 1 NOT NULL;

commit;  

ALTER TABLE MOV_REUNIAO
  DROP CONSTRAINT FK_CAD_PROGRAMAxMOV_REUNIAO;

Alter table CAD_PROGRAMA
  DROP CONSTRAINT XPKCAD_PROGRAMA;

ALTER TABLE CAD_PROGRAMA
       ADD CONSTRAINT XPKCAD_PROGRAMA PRIMARY KEY (
	     DAT_SEMANA,COD_TP_REUNIAO, COD_TP_PARTE);

ALTER TABLE CAD_PROGRAMA
  DROP CONSTRAINT FK_CAD_MOD_REUNIAOxCAD_PROGRAMA;

Delete From cad_programa 
  where (cod_tp_reuniao||'-'||cod_tp_parte) 
    not in (select cod_tp_reuniao||'-'||cod_tp_parte 
              from cad_mod_reuniao);
commit;  
  
ALTER TABLE CAD_PROGRAMA
       ADD CONSTRAINT FK_CAD_MOD_REUNIAOxCAD_PROGRAMA
              FOREIGN KEY (COD_TP_REUNIAO, COD_TP_PARTE)
                             REFERENCES CAD_MOD_REUNIAO;			  

ALTER TABLE MOV_REUNIAO
       ADD CONSTRAINT FK_CAD_PROGRAMAxMOV_REUNIAO
              FOREIGN KEY (DAT_SEMANA, COD_TP_REUNIAO, COD_TP_PARTE)
                             REFERENCES CAD_PROGRAMA;
							 
alter table cad_programa drop constraint FK_CAD_REUNIAOXCAD_PROGRAMA;							 


ALTER TABLE CAD_PROGRAMA
       ADD CONSTRAINT FK_CAD_REUNIAOxCAD_PROGRAMA
              FOREIGN KEY (DAT_SEMANA)
                             REFERENCES CAD_REUNIAO;							 