create view VW_PONTOS_CONCLUIDOS  (COD_PUBLICO, COD_PONTO, DAT_CONCLUSAO)
as
Select
  X.COD_PUBLICO,
  X.COD_PONTO,
  X.DAT_REUNIAO DAT_CONCLUSAO
  From MOV_REUNIAO X
  Where  FLG_CONCLUIU_PONTO = 'S'
Union    
Select
X.COD_PUBLICO,
X.COD_PONTO,
X.DAT_CONCLUSAO
  From CAD_PONTO_CONCLUIDO X

