DROP VIEW VW_MOV_LANCAMENTO;

CREATE VIEW VW_MOV_LANCAMENTO(
NUM_LANCAMENTO,
NOM_DESCRICAO)
AS
Select
NUM_LANCAMENTO,
DAT_LANCAMENTO||' '||VAL_LANCAMENTO||' - '||DSC_LANCAMENTO
From
MOV_LANCAMENTO;